(*********************************************************************************
 * Copyright: AutoMate MX
 * Author: Erick Alcantar 
 * Created:   July 8, 2024/9:54 PM 
 *********************************************************************************
  Programa para procesar las variables que son extraidas via INA2000 protocol
 *********************************************************************************)
	

PROGRAM _INIT

	(* Inicializando las variables declaradas en el DataMap*)
	actPosExtEncoder;
	cutEnabled;

END_PROGRAM


PROGRAM _CYCLIC


(* TODO : Add your code here *)


END_PROGRAM
